apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:mysql://mysql-db-instance-instance-1.cheaaeoyi3rl.us-east-1.rds.amazonaws.com:3306/restaurantdb
  foodcataloguedb_url: jdbc:mysql://mysql-db-instance-instance-1.cheaaeoyi3rl.us-east-1.rds.amazonaws.com:3306/foodcataloguedb
  userdb_url: jdbc:mysql://mysql-db-instance-instance-1.cheaaeoyi3rl.us-east-1.rds.amazonaws.com:3306/userdatadb
  orderdb_url: mongodb+srv://admin:vipulsdb@atlas-cluster.57fba5m.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

# mysql-db-instance.cheaaeoyi3rl.us-east-1.rds.amazonaws.com 




# restaurantdb: restaurantdb
# mysql-server: mysql-service    # The name of mysql service
# mysql-user-username: root
# citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
# foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
# userdb_url: jdbc:mysql://mysql-service:3306/userdb
# foodcataloguedb: foodcataloguedb
# userdb: userdb
