apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp
  labels:
    app: restaurantapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp
  template:
    metadata:
      labels:
        app: restaurantapp
    spec:
      containers:
<<<<<<< HEAD
      - name: restaurantapp
        image: vipskuttu/restaurant-service:2
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: mysql-password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: restaurantdb_url
=======
        - name: restaurantapp
          image: vipskuttu/restaurant-listing-service:2
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: restaurantdb_url
>>>>>>> 7254f97e97d244abc3426240c31323eec38df6ea
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
  selector:
    app: restaurantapp
